version: '3.1'
services:
  db:
    image: mysql:5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${SENHA_ROOT}
      MYSQL_DATABASE: sistema-medicos
    ports:
      - "3307:3306"
    volumes:
      - $HOME/Desktop/MySQL-Snippets/sistema-medicos.sql:/sistema-medicos.sql